name: pms
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  connectivity_plus: ^2.3.6+1

  flutter:
    sdk: flutter
  horizontal_data_table: ^4.1.1+1
  intl: ^0.17.0
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/google.svg
    - assets/phone.svg
    - assets/mavioguz.jpg
