// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcz6ApHlzYh1FnZHwB8hHGeeMfAaGSEGY',
    appId: '1:347135515449:web:9ce854ebe0e65b6fe2e6e8',
    messagingSenderId: '347135515449',
    projectId: 'pfms-f1f4f',
    authDomain: 'pfms-f1f4f.firebaseapp.com',
    storageBucket: 'pfms-f1f4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzajXB4cBcS_6kTqmsNI5O9XvwSU1FSwg',
    appId: '1:347135515449:android:7ce36c7d5314abbee2e6e8',
    messagingSenderId: '347135515449',
    projectId: 'pfms-f1f4f',
    storageBucket: 'pfms-f1f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkA83TPgqaVQIcBVQ3YT8IL52Rht9Fkl0',
    appId: '1:347135515449:ios:1f135b577cf74461e2e6e8',
    messagingSenderId: '347135515449',
    projectId: 'pfms-f1f4f',
    storageBucket: 'pfms-f1f4f.appspot.com',
    iosClientId:
        '347135515449-j8313lcpps9uivom58nred5vudf9mvbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pms',
  );
}
